/** One icon per column kind, shared by the grid headers and the composer's column chips. */
import { AiMagicIcon, Calendar03Icon, HashtagIcon, TextIcon } from '@hugeicons/core-free-icons';
import type { IconSvgElement } from '@hugeicons/svelte';
import type { ColumnKind } from '$lib/core/columns';

export const kindIcons: Record<ColumnKind, IconSvgElement> = {
	generated: AiMagicIcon,
	number: HashtagIcon,
	date: Calendar03Icon,
	text: TextIcon
};

export const kindNames: Record<ColumnKind, string> = {
	generated: 'Generated by a prompt',
	number: 'Numbers',
	date: 'Dates',
	text: 'Text'
};
